apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-simple-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_ME_GIT_REPO_URL
    targetRevision: main
    path: apps/simple-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
