apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-simple-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OmarKhaledKhalil/atos-gitops-project
    targetRevision: main
    path: apps/simple-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
